// <auto-generated />
using MPESA_V2_APIV2_MSISDN_DECRYPTER;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace mpesa_msisdn_hash_decrypt.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240605181513_database_initializer")]
    partial class database_initializer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("MPESA_V2_APIV2_MSISDN_DECRYPTER.PhoneNumber", b =>
                {
                    b.Property<string>("Hash")
                        .HasColumnType("TEXT")
                        .HasColumnName("hash");

                    b.Property<string>("Msisdn")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("msisdn");

                    b.HasKey("Hash");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("MPESA_V2_APIV2_MSISDN_DECRYPTER.UserRecord", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("token");

                    b.HasKey("Name");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
